name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: npm run build --if-present

  test_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Run client tests
        working-directory: ./client
        run: npm test -- --runInBand

  deploy_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: echo "Run Deploy App"
